---
- hosts: localhost
  connection: local
  vars_files:
    - vars/telegram_vars.yml
    - vars/slack.yml

  tasks:
    - name: Sending message to Telegram
      telegram: 
         token: "{{ tokenBot }}"
         chat_id: "{{ chatID }}"
         msg: "SSH terminal interactive for {{ host_or_group }} : {{ tty_on_off }}"
      when: '"Telegram" in notification_tool'

    - name: Sending message to Slack
      slack:
         token: "{{ slack_token }}" 
         channel: "{{ slack_channel }}"
         domain: "{{ slack_domain }}"
         msg: "SSH terminal interactive for {{ host_or_group }} : {{ tty_on_off }}"
      when: '"Slack" in notification_tool'

